---
title: "Reveiw Questions"
output: html_document
---

Informations

Chris: chris.brown **at** decisionpatterns.com
Google Group: CSX460
Github: https://github.com/csx460


All assignments should be submitted to the github repository using a branch created wit you initials. For Example,

    git clone https://github.com/csx460/week2
    git checkout -b ctb
    (work)
    git add ...
    git commit ...
    git push into your repo and issue a pull request.    


Place answers directly in the files.

Feel free to push your answers when you are complete 


Assignments:

* Please Read Chapters 1-3 of Applied Predictive Modeling 


* Submit via email a project proposal: A description of your project that includes:
** The objective, what you expect to achieve with the model
** data source(s)
** responses
** expected (hypothesized) predictors
** how the model will be used 
** how you will determine the measure of success of the model


# 1.  Do the boston-housing.Rmd assignment in github.
Don't forget to show your works, plots included.


# 2. Algorithms and Functions

When speaking of Machine Learning, there are two functions or algorithms involved.
Describe and differentiate the algorithms from the function.
--> A function is a program/module/block of code that takes in one or more inputs and gives you a desired output. On the other hand an algorithm is a precise step-by-step plan for a computational procedure which may involve multiple algorithms or functions with in 

# 2. RMSE and MAE

Why is RMSE preferrable to MAE? 
--> RMSE is preferrable to MAE when we need more sensitivity towards occasional large error, the squaring process gives disproportionate weight to very large errors.

When is MAE better? 
-->  If an occasional large error does not effect your model/ decision 
